/*
    수강신청
    1. 여러 학생이 여러 과목을 신청하는 다대다관계
    2. 학생-과목의 직접적인 다대다관계 설정은 불가능
    3. 학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
*/
/*
    참고. 외래키 제약조건을 무시하고 테이블 삭제
    순서에 상관없이 삭제할 수 있음
*/
    DROP TABLE STUDENTLIST CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE APPCLASS  CASCADE CONSTRAINTS;



DROP TABLE APPCLASS;
DROP TABLE SUBJECT;
DROP TABLE STUDENTLIST;

CREATE TABLE STUDENTLIST(
    STU_NO CHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NULL,
    STU_AGE NUMBER(3) NULL,
    CONSTRAINT PK_STUDENTLIST PRIMARY KEY(STU_NO),
    CONSTRAINT STU_AGE CHECK(STU_AGE BETWEEN 0 AND 100)
);

CREATE TABLE SUBJECT(
    SUBJ_CODE CHAR(1 BYTE) NOT NULL,
    SUBJ_NAME VARCHAR2(20 BYTE) NOT NULL,
    SUBJ_PROF VARCHAR2(20 BYTE) NUll,
    CONSTRAINT PK_SUBJ PRIMARY KEY(SUBJ_CODE)
);

CREATE TABLE APPCLASS(
    APP_NO NUMBER(1) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUBJ_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_APPCLASS PRIMARY KEY(APP_NO),
    CONSTRAINT FK_APPCLASS_STUDENTLIST FOREIGN KEY(STU_NO) REFERENCES STUDENTLIST(STU_NO),
    CONSTRAINT FK_APPCLASS_SUBJECT FOREIGN KEY(SUBJ_CODE) REFERENCES SUBJECT(SUBJ_CODE)
);