
CREATE TABLE STUDENT(
 STU_NO NUMBER(5) NOT NULL,
STU_NAME VARCHAR2(20 BYTE) NOT NULL,
STU_ADDR VARCHAR2(100 BYTE), 
STU_GRADE NUMBER,
STU_PROF_NO NUMBER(5)
);

CREATE TABLE PROFESSOR(
PROF_NO NUMBER(5),
PROF_NAME VARCHAR2(20 BYTE) NOT NULL,
PROF_MAJOR VARCHAR2(40 BYTE) NOT NULL
);

CREATE TABLE LECTURE(
LECT_NUMBER(8)

);

CREATE TABLE EMROLL(
);

CREATE TABLE COURSE(
);