DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,  -- 게시글번호
	WRITER VARCHAR2(100 BYTE),  -- 작성자
	TITLE VARCHAR2(1000 BYTE) NOT NULL,  -- 제목
    CONTENT VARCHAR2(4000 BYTE),  -- 내용
    IP VARCHAR2(50 BYTE),  -- 작성IP
	HIT NUMBER,  -- 조회수
	CREATE_DATE DATE,  -- 작성일
    MODIFY_DATE DATE  -- 수정일
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ;