-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE INCREMENT BY 1 START WITH 1000;

-- 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD(
   	BOARD_NO NUMBER NOT NULL,
    WRITER 	 VARCHAR2(100 BYTE) NOT NULL, 
    TITLE    VARCHAR2(100 BYTE) NOT NULL,
    CONTENT  VARCHAR2(400 BYTE),
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '관리자', '공지', '불났다', SYSDATE);
COMMIT