DROP TABLE GOOD;
DROP TABLE COMMENTS;
DROP TABLE SUMMERNOTE_IMAGE;
DROP TABLE BLOG;
DROP TABLE USERS;

-- 사용자
CREATE TABLE USERS
(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(50 BYTE) NOT NULL,
    PW VARCHAR2(25 BYTE),
    NAME VARCHAR2(50 BYTE) NOT NULL
);

-- 블로그
CREATE TABLE BLOG
(
    BLOG_NO NUMBER NOT NULL,
    TITLE VARCHAR2(500 BYTE) NOT NULL,
    CONTENT CLOB,
    HIT NUMBER NOT NULL,
    IP VARCHAR2(32 BYTE) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    MODIFY_DATE DATE NOT NULL,
    USER_NO NUMBER NOT NULL  -- 외래키
);

-- 써머노트에서 사용된 이미지 목록(시퀀스는 사용하지 않음)
CREATE TABLE SUMMERNOTE_IMAGE
(
    BLOG_NO NUMBER,  -- 외래키
    FILESYSTEM VARCHAR2(40 BYTE)
);

-- 댓글(1단 계층형)
CREATE TABLE COMMENTS
(
    COMMENT_NO NUMBER NOT NULL,
    BLOG_NO NUMBER,             -- 외래키 (ON DELETE SET NULL을 위해 NOT NULL 처리하면 안 됨)
    CONTENT VARCHAR2(4000 BYTE) NOT NULL,
    STATE NUMBER NOT NULL,      -- 정상 1, 삭제 -1
    DEPTH NUMBER NOT NULL,      -- 댓글 0, 댓글의 답글 1
    GROUP_NO NUMBER NOT NULL,   -- 댓글과 해당 댓글에 달린 답글은 같은 그룹
    CREATE_DATE DATE NOT NULL,
    USER_NO NUMBER NOT NULL  -- 외래키
);

-- 좋아요
CREATE TABLE GOOD (
    USER_NO NUMBER NOT NULL,
    BLOG_NO NUMBER NOT NULL,
    MARK_DATE DATE NOT NULL
);

-- 사용자 기본키
ALTER TABLE USERS
    ADD CONSTRAINT PK_USERS
        PRIMARY KEY(USER_NO);

-- 블로그 기본키
ALTER TABLE BLOG
    ADD CONSTRAINT PK_BLOG
        PRIMARY KEY(BLOG_NO);

-- 댓글 기본키
ALTER TABLE COMMENTS
    ADD CONSTRAINT PK_COMMENTS
        PRIMARY KEY(COMMENT_NO);

-- 블로그 외래키 : 작성자를 삭제하면 블로그도 함께 삭제된다.
ALTER TABLE BLOG
    ADD CONSTRAINT FK_BLOG_USERS
        FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO)
            ON DELETE CASCADE;

-- 서머노트 이미지 외래키 : 블로그를 삭제하면 써머노트에서 사용한 이미지 파일도 삭제한다.
ALTER TABLE SUMMERNOTE_IMAGE
    ADD CONSTRAINT FK_SUMMERNOTE_BLOG
        FOREIGN KEY(BLOG_NO) REFERENCES BLOG(BLOG_NO)
            ON DELETE CASCADE;

-- 댓글 외래키 : 댓글이 존재하는 블로그를 삭제하면 댓글의 BLOG_NO가 NULL 처리된다.
ALTER TABLE COMMENTS
    ADD CONSTRAINT FK_COMMENTS_BLOG
        FOREIGN KEY(BLOG_NO) REFERENCES BLOG(BLOG_NO)
            ON DELETE SET NULL;

-- 시퀀스
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE BLOG_SEQ;
DROP SEQUENCE COMMENTS_SEQ;

CREATE SEQUENCE USERS_SEQ NOCACHE;
CREATE SEQUENCE BLOG_SEQ NOCACHE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE;

-- 사용자 데이터
INSERT INTO USERS(USER_NO, ID, PW, NAME) VALUES(USERS_SEQ.NEXTVAL, 'ryan', '1111', '라이언');
INSERT INTO USERS(USER_NO, ID, PW, NAME) VALUES(USERS_SEQ.NEXTVAL, 'apeach', '1111', '어피치');
INSERT INTO USERS(USER_NO, ID, PW, NAME) VALUES(USERS_SEQ.NEXTVAL, 'prodo', '1111', '프로도');
COMMIT;
